"""
Pydantic Schemas — Data Validation Models
==========================================
Defines input/output models for API endpoints.
Each group corresponds to a domain: Auth, Profile, Roadmap, Admin.

Convention:
  - *Request  → data sent by the client
  - *Response → data returned by the API
"""

from typing import Optional, List, Dict, Any
from pydantic import BaseModel, Field


# ──────────────────────────────────────────────
# COMMON — Reusable across domains
# ──────────────────────────────────────────────


class MessageResponse(BaseModel):
    """Generic response with a text message."""

    message: str


# ──────────────────────────────────────────────
# AUTH — Registration and login
# ──────────────────────────────────────────────


class RegisterRequest(BaseModel):
    """Data required to register a new user."""

    email: str = Field(..., description="User email address")
    password: str = Field(..., min_length=8, description="Password (min 8 characters)")
    name: str = Field(..., description="User full name")


class LoginRequest(BaseModel):
    """Credentials for logging in."""

    email: str = Field(..., description="Registered email address")
    password: str = Field(..., description="User password")


class TokenResponse(BaseModel):
    """Response with JWT token after successful authentication."""

    access_token: str = Field(..., description="JWT access token")
    token_type: str = Field(default="bearer", description="Token type")
    user_id: str = Field(..., description="Authenticated user ID")
    name: str = Field(..., description="User name")


# ──────────────────────────────────────────────
# PROFILE — User cognitive profile
# ──────────────────────────────────────────────


class QuestionnaireAnswers(BaseModel):
    """Questionnaire answers submitted from the frontend."""

    user_id: str = Field(..., description="User ID")
    answers: Dict[str, Any] = Field(
        ...,
        description=(
            "Dictionary with questionnaire answers. "
            "Key = question ID, Value = user answer"
        ),
    )


class CompetencyScore(BaseModel):
    """Score for an individual competency."""

    competency_id: str
    name: str
    level: str = Field(..., description="Detected level: low/medium/high")
    score: float = Field(..., ge=0, le=1, description="Normalized score 0-1")


class CompetencyProfile(BaseModel):
    """Cognitive profile generated by the Profiling Agent."""

    user_id: str
    profile_id: str
    competencies: List[CompetencyScore] = Field(
        default_factory=list,
        description="List of evaluated competencies with their scores",
    )
    recommended_approach: str = Field(
        ...,
        description="Recommended trajectory: GENERALIST or SPECIALIST",
    )
    summary: str = Field(
        ..., description="Text summary of the profile generated by the agent"
    )


# ──────────────────────────────────────────────
# ROADMAP — Generation and management
# ──────────────────────────────────────────────


class RoadmapGenerateRequest(BaseModel):
    """Data to request generation of a personalized roadmap."""

    user_id: str = Field(..., description="User ID")
    approach: str = Field(
        ...,
        description="Preferred trajectory: GENERALIST or SPECIALIST",
    )


class RoadmapBlock(BaseModel):
    """A block (course) within a roadmap phase."""

    block_id: str
    content_id: str = Field(..., description="Course ID in the catalog")
    title: str
    order: int
    completed: bool = False


class RoadmapPhase(BaseModel):
    """A roadmap phase with its blocks."""

    phase_order: int
    name: str
    blocks: List[RoadmapBlock] = Field(default_factory=list)


class RoadmapResponse(BaseModel):
    """Complete roadmap generated for a user."""

    roadmap_id: str
    user_id: str
    approach: str
    phases: List[RoadmapPhase] = Field(default_factory=list)
    explanation: str = Field(
        ...,
        description="Explanatory Agent's reasoning for why this roadmap is recommended",
    )


class AlternativesResponse(BaseModel):
    """Both trajectories (generalist and specialist) for a roadmap."""

    roadmap_id: str
    generalist: Optional[RoadmapResponse] = None
    specialist: Optional[RoadmapResponse] = None


class BlockProgressUpdate(BaseModel):
    """Data to mark a block as completed."""

    completed: bool = Field(
        True, description="Mark as completed (True) or pending (False)"
    )


# ──────────────────────────────────────────────
# ADMIN — Administration panel management
# ──────────────────────────────────────────────


class CourseCreate(BaseModel):
    """Data to create a new course."""

    title: str
    description: str
    level: str = Field(..., description="beginner/intermediate/advanced")
    affinity: str = Field(..., description="generalist/specialist/both")
    competencies: List[str] = Field(default_factory=list)
    duration_hours: int = Field(0, ge=0)
    url: Optional[str] = None


class CourseUpdate(BaseModel):
    """Optional fields to update a course."""

    title: Optional[str] = None
    description: Optional[str] = None
    level: Optional[str] = None
    affinity: Optional[str] = None
    competencies: Optional[List[str]] = None
    duration_hours: Optional[int] = None
    url: Optional[str] = None


class CourseResponse(BaseModel):
    """Response with course data."""

    id: str
    title: str
    description: str
    level: str
    affinity: str
    competencies: List[str] = Field(default_factory=list)
    duration_hours: int = 0
    url: Optional[str] = None


class UserStatusUpdate(BaseModel):
    """Data to activate/deactivate a user."""

    is_active: bool


class RoadmapBlockAdd(BaseModel):
    """Data to add a block to a roadmap."""

    phase_order: int
    content_id: str
    position: Optional[int] = None


class RoadmapBlockRemove(BaseModel):
    """Data to remove a block from a roadmap."""

    phase_order: int
    content_id: str
