"""
Schemas Pydantic — Modelos de validación de datos
==================================================
Define los modelos de entrada/salida para los endpoints de la API.
Cada grupo corresponde a un dominio: Auth, Profile, Roadmap, Admin.

Convención:
  - *Request  → datos que envía el cliente
  - *Response → datos que devuelve la API
"""

from typing import Optional, List, Dict, Any
from pydantic import BaseModel, EmailStr, Field


# ──────────────────────────────────────────────
# COMÚN — Reutilizable en varios dominios
# ──────────────────────────────────────────────

class MessageResponse(BaseModel):
    """Respuesta genérica con un mensaje de texto."""
    message: str


# ──────────────────────────────────────────────
# AUTH — Registro e inicio de sesión
# ──────────────────────────────────────────────

class RegisterRequest(BaseModel):
    """Datos requeridos para registrar un nuevo usuario."""
    email: str = Field(..., description="Correo electrónico del usuario")
    password: str = Field(..., min_length=8, description="Contraseña (mín. 8 caracteres)")
    nombre: str = Field(..., description="Nombre completo del usuario")


class LoginRequest(BaseModel):
    """Credenciales para iniciar sesión."""
    email: str = Field(..., description="Correo electrónico registrado")
    password: str = Field(..., description="Contraseña del usuario")


class TokenResponse(BaseModel):
    """Response with JWT token after successful authentication."""
    access_token: str = Field(..., description="Access JWT")
    token_type: str = Field(default="bearer", description="Token type")
    user_id: str = Field(..., description="ID of the authenticated user")
    name: str = Field(..., description="Name of the user")


# ──────────────────────────────────────────────
# PROFILE — Perfil cognitivo del usuario
# ──────────────────────────────────────────────

class QuestionnaireAnswers(BaseModel):
    """Answers from the questionnaire sent from the frontend."""
    user_id: str = Field(..., description="Unique ID of the user")
    currentRole: str = Field(..., description="Current role of the user")
    experience: int = Field(..., description="Years of experience")
    competencies: Dict[str, int] = Field(..., description="Map of competency ID to level (1-4)")
    targetRole: str = Field(..., description="Desired target role")
    deadline: str = Field(..., description="Deadline for reaching the target")
    learningStyle: str = Field(..., description="Learning style (autodidacta/guiado)")
    pace: str = Field(..., description="Learning pace (intensivo/gradual)")


class CompetencyScore(BaseModel):
    """Score for an individual competency."""
    id: str = Field(..., alias="competency_id")
    label: str = Field(..., alias="name")
    domain: str = Field(default="General")
    current_level: int = Field(..., ge=1, le=4)
    target_level: int = Field(default=4)
    gap: int = Field(default=0)
    score: float = Field(..., ge=0, le=1)

    class Config:
        allow_population_by_field_name = True


class CompetencyProfile(BaseModel):
    """Cognitive profile generated by the Profiling Agent."""
    user_id: str
    profile_id: str
    current_role: str = Field(..., description="Role reported in the questionnaire")
    target_role: str = Field(..., description="Desired role reported in the questionnaire")
    experience_years: int = Field(..., description="Years of experience reported")
    competencies: List[CompetencyScore] = Field(
        default_factory=list,
        description="List of evaluated competencies with scores",
    )
    recommended_approach: str = Field(
        ...,
        description="Recommended path: GENERALIST or SPECIALIST",
    )
    summary: str = Field(..., description="Textual summary of the profile")


class AvatarState(BaseModel):
    """Visual and personality state of the digital twin."""
    url: Optional[str] = None
    personality: Optional[str] = None
    color: Optional[str] = None



# ──────────────────────────────────────────────
# ROADMAP — Generación y gestión de roadmaps
# ──────────────────────────────────────────────

class RoadmapGenerateRequest(BaseModel):
    """Data to request the generation of a personalized roadmap."""
    user_id: str = Field(..., description="ID of the user")
    approach: str = Field(
        ...,
        description="Preferred path: GENERALIST or SPECIALIST",
    )


class RoadmapBlock(BaseModel):
    """A block (course) within a roadmap phase."""
    id: str = Field(..., alias="block_id")
    course_id: str = Field(..., alias="content_id")
    title: str
    order: int
    completed: bool = False
    priority: str = Field(default="required")
    duration: str = Field(default="8h")
    level: str = Field(default="intermediate")
    why: str = Field(default="")
    competencies_addressed: List[str] = Field(default_factory=list)

    class Config:
        allow_population_by_field_name = True


class RoadmapPhase(BaseModel):
    """A roadmap phase with its blocks."""
    phase_order: int
    name: str
    blocks: List[RoadmapBlock] = Field(default_factory=list)


class RoadmapResponse(BaseModel):
    """Complete roadmap generated for a user."""
    roadmap_id: str
    user_id: str
    approach: str
    phases: List[RoadmapPhase] = Field(default_factory=list)
    explanation: str = Field(
        ...,
        description="Explanation from the Explanatory Agent on why this roadmap is recommended",
    )


class FullProfileResponse(BaseModel):
    """Unified state for the frontend (Profile + Radar + Roadmap + Avatar)."""
    user_id: str
    full_name: str
    current_role: str
    target_role: str
    experience_years: int
    avatar: AvatarState
    competency_profile: Optional[CompetencyProfile] = None
    roadmap: Optional[RoadmapResponse] = None


class AlternativesResponse(BaseModel):
    """Both trajectories (generalist and specialist) for a roadmap."""
    roadmap_id: str
    generalist: Optional[RoadmapResponse] = None
    specialist: Optional[RoadmapResponse] = None


class BlockProgressUpdate(BaseModel):
    """Data to mark a block as completed."""
    completed: bool = Field(True, description="Mark as completed (True) or pending (False)")


# ──────────────────────────────────────────────
# ADMIN — Gestión del panel de administración
# ──────────────────────────────────────────────
# (Usados ya por admin.py)

class CourseCreate(BaseModel):
    """Data to create a new course."""
    title: str
    description: str
    level: str = Field(..., description="beginner/intermediate/advanced")
    affinity: str = Field(..., description="generalist/specialist/both")
    competencies: List[str] = Field(default_factory=list)
    duration_hours: int = Field(0, ge=0)
    url: Optional[str] = None


class CourseUpdate(BaseModel):
    """Optional fields to update a course."""
    title: Optional[str] = None
    description: Optional[str] = None
    level: Optional[str] = None
    affinity: Optional[str] = None
    competencies: Optional[List[str]] = None
    duration_hours: Optional[int] = None
    url: Optional[str] = None


class CourseResponse(BaseModel):
    """Response with course data."""
    id: str
    title: str
    description: str
    level: str
    affinity: str
    competencies: List[str] = Field(default_factory=list)
    duration_hours: int = 0
    url: Optional[str] = None


class UserStatusUpdate(BaseModel):
    """Datos para activar/desactivar un usuario."""
    is_active: bool


class RoadmapBlockAdd(BaseModel):
    """Data to add a block to a roadmap."""
    phase_order: int
    content_id: str
    position: Optional[int] = None


class RoadmapBlockRemove(BaseModel):
    """Data to remove a block from a roadmap."""
    phase_order: int
    content_id: str
